---
title: "Schedule"
author: "Davi Moreira"
# date-modified: "last-modified"
date: "2024-08-01"
date-format: "MMM D, YYYY"
# listing:
#   - id: schedule
#     contents:
#       - topics/topic-*.qmd
#     type: table
#     fields: [week, title, subtitle, date]
#     field-display-names:
#       week: "Week"
#       title: "Topic"
#       description: "Dates"
#       subtitle: "Description"
#     date-format: "MMMM DD, YYYY to MMMM DD, YYYY"
#     sort: [filename]
#     sort-ui: false
#     filter-ui: false
 #tbl-colwidths: [5,20,50,25]
editor: visual
---

| **Date**     | **Topic**                                                                  | **Assignment (due dates on Brightspace)** | **Slides\*\***                                                                                                                                                                                                                  | **Supplementary Materials**                                                                                                                                                                                                                                                                                                                                                  |
|--------------|-------------------|--------------|--------------|--------------|
| **8/19/24**  | Lesson 1: Technical Enablers of Modern Data-Driven Decision Making         | Quiz #1<br>Exercise #1                    | [slides](/lecture_slides/01_lesson_m3dm/01_lesson_m3dm.html){target="_blank"}                                                                                                                                                   | \- [**Video**: The NBA Data Scientist](https://www.youtube.com/watch?v=MpLHMKTolVw&list=PLkIselvEzpM5nFf4nu--q2OGccA_0alYO){target="_blank"}<br>- [**Video**: Hans Rosling's 200 Countries, 200 Years](https://www.youtube.com/watch?v=jbkSRLYSojo&list=PLkIselvEzpM5nFf4nu--q2OGccA_0alYO&index=1){target="_blank"}                                                         |
| **8/26/24**  | Lesson 2: Data Organization for Using Data to Drive Decisions              | Quiz #2<br>Exercise #2                    | [slides](/lecture_slides/02_lesson_m3dm/02_lesson_m3dm.html){target="_blank"}                                                                                                                                                   | \- [**Video**: Relational vs. Non-Relational Databases](https://www.youtube.com/watch?v=E9AgJnsEvG4){target="_blank"}                                                                                                                                                                                                                                                        |
| **9/2/24**   | No class\* - Labor Day - Lesson 3: Tools for Using Data to Drive Decisions | Quiz #3<br>Exercise #3                    |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                              |
| **9/9/24**   | Lesson 4: Introduction to R and RStudio                                    | Quiz #4<br>Exercise #4                    | [slides](/lecture_slides/04_lesson_m3dm/04_lesson_m3dm.html){target="_blank"}<br>[script](/lecture_slides/04_lesson_m3dm/04_lesson_m3dm.R){target="_blank"}                                                                     | \- [**Video**: RStudio is now Posit!](https://www.youtube.com/watch?v=0_UNtwEh7kY){target="_blank"}                                                                                                                                                                                                                                                                          |
| **9/16/24**  | Lesson 5: Installing Packages and Importing Data in R                      | Quiz #5<br>Exercise #5                    | [slides](/lecture_slides/05_lesson_m3dm/05_lesson_m3dm.html){target="_blank"}<br>[script](/lecture_slides/05_lesson_m3dm/05_lesson_m3dm.R){target="_blank"}<br>[data](/lecture_slides/05_lesson_m3dm/data.zip){target="_blank"} | \- [**Video**: It's a Great Time to be an R Package Developer!](https://www.youtube.com/watch?v=hfqjyeA_z7s){target="_blank"}<br>- [Blog: Quick list of useful R packages](https://support.posit.co/hc/en-us/articles/201057987-Quick-list-of-useful-R-packages){target="_blank"}<br>- [Posit R packages](https://posit.co/products/open-source/rpackages/){target="_blank"} |
| **9/23/24**  | Lesson 6: Data Types and Viewing Data Types in R                           | Quiz #6<br>Exercise #6                    | [slides](/lecture_slides/06_lesson_m3dm/06_lesson_m3dm.html){target="_blank"}<br>[script](/lecture_slides/06_lesson_m3dm/06_lesson_m3dm.R){target="_blank"}<br>[data](/lecture_slides/06_lesson_m3dm/data.zip){target="_blank"}                 | - [R Data Types](https://www.w3schools.com/r/r_data_types.asp){target="_blank"}<br>- [Dates with Lubridate](https://lubridate.tidyverse.org/){target="_blank"}<br>- [Categorical Data](https://sscc.wisc.edu/sscc/pubs/dwr/categorical.html#cheat-sheet){target="_blank"} |
| **9/30/24**  | Lesson 7: Key Steps of Performing Data Mining in R                         | Quiz #7<br>Exercise #7      | [slides](/lecture_slides/07_lesson_m3dm/07_lesson_m3dm.html){target="_blank"}<br>[script](/lecture_slides/07_lesson_m3dm/07_lesson_m3dm.R){target="_blank"} |  - [Blog: Data Mining in R](https://www.geeksforgeeks.org/data-mining-in-r/){target="_blank"}<br> - [Blog: Data Mining with R](https://rpubs.com/uriel623/670548){target="_blank"} |
| **10/7/24**  | No class\* - Fall Break - Lesson 8: Most Applied Data Mining Techniques    | Quiz #8<br>Exercise #8                    | .                                                                                                                                                                                                                               | .                                                                                                                                                                                                                                                                                                                                                                            |
| **10/14/24** | Lesson 9: Exploratory Data Analysis in R: Summary Statistics               | Quiz #9<br>Exercise #9                    | [slides](/lecture_slides/09_lesson_m3dm/09_lesson_m3dm.html){target="_blank"}<br>[script](/lecture_slides/09_lesson_m3dm/09_lesson_m3dm.R){target="_blank"} |  - [R4DS: Exploratory Data Analysis](https://r4ds.hadley.nz/eda){target="_blank"}<br> - [IBM: What is Exploratory Data Analysis?](https://www.ibm.com/topics/exploratory-data-analysis){target="_blank"} |
| **10/21/24** | Lesson 10: Exploratory Data Analysis in R: Visualization and Dashboarding  | Quiz #10<br>Exercise #10                  | [slides](/lecture_slides/10_lesson_m3dm/10_lesson_m3dm.html){target="_blank"}<br>[script](/lecture_slides/10_lesson_m3dm/10_lesson_m3dm.R){target="_blank"} | - [R4DS: Visualize](https://r4ds.hadley.nz/visualize){target="_blank"}<br> - [Hadley Wickham's Lecture](http://stat405.had.co.nz/lectures/20-effective-vis.pdf){target="_blank"}<br> - [r-graph-gallery](https://www.r-graph-gallery.com/){target="_blank"}<br> - [ggplot flipbook](https://evamaerey.github.io/ggplot_flipbook/ggplot_flipbook_xaringan.html#1){target="_blank"}<br> - [Gallery](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html){target="_blank"}<br> - [Edward Tufte](https://www.edwardtufte.com/tufte/){target="_blank"}  |
| **10/28/24** | Lesson 11: Mine Data through Predictive Modeling in R                      | Quiz #11<br>Exercise #11                  | [slides](/lecture_slides/11_lesson_m3dm/11_lesson_m3dm.html){target="_blank"}<br>[script](/lecture_slides/11_lesson_m3dm/11_lesson_m3dm.R){target="_blank"} | - [**Video**: Line Fitting, Residuals, and Correlation](https://www.youtube.com/watch?v=mPvtZhdPBhQ&list=PLkIselvEzpM63ikRfN41DNIhSgzboELOM){target="_blank"}<br> - [**Video**: Fitting a Line with Least Squares Regression](https://www.youtube.com/watch?v=z8DmwG2G4Qc&list=PLkIselvEzpM63ikRfN41DNIhSgzboELOM){target="_blank"}<br> - [**Video**: Least Squares Regression](https://www.youtube.com/watch?v=yqf0L_WEaW0&list=PLkIselvEzpM63ikRfN41DNIhSgzboELOM){target="_blank"}<br> - [**Video**: Types of Outliers in Linear Regression](https://www.youtube.com/watch?v=jZEKAlo1E54&list=PLkIselvEzpM63ikRfN41DNIhSgzboELOM){target="_blank"}<br> - [**Video**: Inference for Linear Regression](https://www.youtube.com/watch?v=depiT-hTaGA&list=PLkIselvEzpM63ikRfN41DNIhSgzboELOM){target="_blank"}<br> -[IMS: Linear regression with a single predictor](https://openintro-ims.netlify.app/model-slr){target="_blank"}<br> -[IMS: Inference for linear regression with a single predictor](https://openintro-ims.netlify.app/inf-model-slr){target="_blank"}<br>- [**Video**: Introduction to Multiple Regression](https://www.youtube.com/watch?v=sQpAuyfEYZg&list=PLkIselvEzpM5f1HYzIjFt52SD4izsJ2_I){target="_blank"}<br>- [**Video**: Model Selection in Multiple Regression](https://www.youtube.com/watch?v=VB1qSwoF-l0&list=PLkIselvEzpM5f1HYzIjFt52SD4izsJ2_I){target="_blank"}<br>- [**Video**: Checking Multiple Regression Diagnostics Using Graphs](https://www.youtube.com/watch?v=3KSUeYMKt5A&list=PLkIselvEzpM5f1HYzIjFt52SD4izsJ2_I){target="_blank"}<br>-[IMS: Linear regression with multiple predictors](https://openintro-ims.netlify.app/model-mlr){target="_blank"}<br>-[IMS: Inference for linear regression with multiple predictors](https://openintro-ims.netlify.app/inf-model-mlr){target="_blank"} |
| **11/4/24**  | Lesson 12: Identifying Significant Predictors                              | Quiz #12<br>Exercise #12                  | [slides](/lecture_slides/12_lesson_m3dm/12_lesson_m3dm.html){target="_blank"}<br>[script](/lecture_slides/12_lesson_m3dm/12_lesson_m3dm.R){target="_blank"} | - [**`R` Package**: Variable Selection Methods](https://cran.r-project.org/web/packages/olsrr/vignettes/variable_selection.html){target="_blank"}<br> - [IMS: Model Selection](https://openintro-ims.netlify.app/model-mlr.html#sec-model-selection){target="_blank"}  |
| **11/11/24** | Lesson 13: Predictive Model Interpretations and Predictions                | Quiz #13<br>Exercise #13                  | [slides](/lecture_slides/13_lesson_m3dm/13_lesson_m3dm.html){target="_blank"}<br>[script](/lecture_slides/13_lesson_m3dm/13_lesson_m3dm.R){target="_blank"}                                                                                                                                                                                                                                | - [IMS: Inference for linear regression with multiple predictors](https://openintro-ims.netlify.app/inf-model-mlr.html){target="_blank"}<br> - [IMS: Applications: Model and infer](https://openintro-ims.netlify.app/inf-model-applications){target="_blank"}                                                                                                                                                                                                                                                                                                                                                                             |
| **11/18/24** | Lesson 14: Evaluating Predictive Model Performance                         | Quiz #14<br>Exercise #14                  | [slides](/lecture_slides/14_lesson_m3dm/14_lesson_m3dm.html){target="_blank"}<br>[script](/lecture_slides/14_lesson_m3dm/14_lesson_m3dm.R){target="_blank"}                                                                                                                                                                                                                               | .                                                                                                                                                                                                                                                                                                                                                                            |
| **11/25/24** | Lesson 15: Bringing It All Together: From Data to Insights to Decisions    | Quiz #15<br>Exercise #15                  | [slides](/lecture_slides/15_lesson_m3dm/15_lesson_m3dm.html){target="_blank"}<br>[script](/lecture_slides/15_lesson_m3dm/15_lesson_m3dm.R){target="_blank"}                                                                                                                                                                                                                                                                                                  | - [**Video**: Quarto Dashboards 1: Hello, Dashboards!](https://www.youtube.com/watch?v=HW7QbqI4fH0&list=PL9HYL-VRX0oTCvag75m8yDjFoJvE-gMxp){target="_blank"}<br> - [**Video**: Shiny New Things Using R Bridge the Gap in Electronic Medical Record Reporting](https://posit.co/resources/videos/shiny-new-things-using-r-bridge-the-gap-in-electronic-medical-record-reporting/){target="_blank"}<br>                                                                                                                                                                                                                                                                                                                                                                             |
| **12/2/24**  | Project presentation and report due                                        | **Project presentation submission**       | .                                                                                                                                                                                                                               | .                                                                                                                                                                                                                                                                                                                                                                            |
| **12/9/24**  | Final Exam (online) 4:00 PM - 6:00 PM                                      | .                                         | .                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                                                                                                              |

\*Please note that for the two classes missed due to holidays and breaks, there will be no make-up sessions. However, students are expected to independently complete the assigned readings and exercises during these periods. While class discussions won't take place, engaging with the materials and teammates will ensure you stay on track with the course content.

\*\* Course material adapted from the textbook and previous course editions to better fit our curriculum. Thanks to Professor Zhiwei Zhu, Dr. Z.Z, for guidance and for generously sharing the materials.
